config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => "users/registrations",
    :passwords => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  devise_scope :user do
    delete '/users_icon', to:'users/registrations#delete_icon'
  end
  namespace :admin do
    namespace :member do
      resource :authority, :only => [:show, :update]
      resource :request, :only => [:show, :update]
    end
    namespace :settings do
      resource :slack, :only => [:show, :update]
    end
  end

  resources :products, :only => [:index,:create, :show,:update, :destroy] do
    collection do
      post :import
    end
    resource :tags, :only => [:show,:create, :destroy]
  end
  
  scope :admin do
    resources :products, :only => [:new,:edit] do
      collection do
        get :import_export
      end
    end
    match 'products' => 'products#admin_index', :via => :get, as: 'admin_products'
    match 'lendings' => 'products#admin_lendings', :via => :get, as: 'admin_lendings'
    delete 'products/:id/image', to:'products#delete_image'
  end
  
  resources :lending, :only => [:create, :update]

  namespace :third do
    resource :product_search, :only => [:show]
    match 'image' => 'product_image#show', :via => :get, as: 'load_image'
  end

  resources :lendings
  resources :comments, :only => [:index,:create, :update, :destroy]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @products = Product.last(6).reverse
    @lendings = Product.unreturned.last(6).reverse
    @tags = ActsAsTaggableOn::Tag.most_used(20)
    @comments = Comment.last(3).reverse
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/sp/_home.html.erb
<h1>ホーム</h1>
<%= render "home/sp/side"%>
<%= render "home/sp/new_goods"%>
<%= render "home/sp/new_comments"%>

app/views/home/sp/_introduction.html.erb
<div class="intro_top">
<h1>
  あなたとTansu<br>
  いますぐログイン
</h1>
<p>Tansuは洗練されたWebUIとシンプルな操作感が特徴の備品管理システムです．
<br>備品の登録・管理・貸出を支援し、備品の利用促進と管理コストの縮減を実現します。</p>
<div class="vertical_links">
  <%= link_to "ログイン",new_user_session_path, class: "link_btn link_btn_large link_btn_success"%>
  <%= link_to "新規登録",new_user_registration_path, class: "link_btn link_btn_large link_btn_success"%>
</div>
<hr>
</div>
<div class="l-grid-row intro_box clearfix">
  <div class="l-grid-row">
    <%= image_tag "intro1.png", class: "intro1"%>
  </div>
  <div class="l-grid-row">
    <h2>ミントを想起させる<br>
      清涼なカラーデザイン</h2>
    <p>
      ミントは爽快感と冷涼感をわたしたちに与えます．<br>
      ミントの活躍はとどまるところを知らず，歯磨き粉からアイスクリームなど，様々なものに利用されています．<br>
      Tansuは全面的にミントカラーを採用したため，いつでも爽快感を感じながら備品管理をすることが出来ます．
      
    </p>
  </div>
  
  <div class="l-grid-row">
    <%= image_tag "intro2.png", class: "intro2"%>
  </div>
  <div class="l-grid-row">
        <h2>スマホにも一応対応</h2>
    <p>そこそこスマホからでも使えます。<br>
      スマホ対応をすることで、開発工数が大幅に増えることをご存知ですか？
      Tansuでは、PC版のデザインを大胆に使いまわすことで大幅な工数の削減を実現しました。<br>
      といっても、レスポンシブデザインではありません。PC版とスマートフォン版で、違うページを配信しています。<br>
      また、中途半端なスマホ版表示が気に入らない人向けに、PC版の表示に切り替える機能も用意しました。
      <br>※スマートフォン版では一部機能が対応していません。</p>
  </div>
  
  
</div>

app/views/home/sp/_new_comments.html.erb
<div class="l-grid-row">
  <h2 class="block_heading">新しいレビュー</h2>
</div>
<div class="l-grid-row clearfix">
  <% @comments.each do |comment| %>
    <div class="l-grid-row l-align-left">
      <div class="block_content product_small clearfix">
	<div class="info l-grid-row">
	  <span class="date">
	    <%= l comment.created_at, format: :short %>
	  </span>
	</div>
	<div class="l-grid-row clearfix">
	  <div class="l-grid-1-2 l-align-left">
	    <div class="inner_offset">
	      <% unless comment.product.lendable? %>
		<span class="hover_batch">貸出中</span>
	      <% end %>
	      <%= link_to image_tag(comment.product.image.url), product_path(comment.product)%>
	    </div>
	  </div>
	  <div class="l-grid-1-2 l-align-left">
	    <%= link_to truncate(comment.product.name, :length => 30, :separator => "..."), product_path(comment.product)%>
	  </div>
	</div>
	<div class="l-grid-row clearfix">
	  <div class="product_comment clearfix">
	    <div class="l-grid-3-12 l-align-left">
	      <div class="inner_offset">
		<%= image_tag(comment.user.image.url)%>
		
	      </div>
	    </div>
	    <div class="l-grid-9-12 l-align-left">
	      <div class="l-grid-row">
		<span><%= comment.user.name%></span>
	      </div>
	      <div class="fbox">
		<%= truncate(comment.content, :length => 30, :separator => '...')%>
	      </div>
	    </div>
	  </div>
	</div>
      </div>
    </div>
  <% end %>
</div>
<div class="l-grid-row see_more">
  <%= link_to "さらにみる", comments_path%>
</div>

app/views/home/sp/_new_goods.html.erb
<div class="l-grid-row">
  <h2 class="block_heading">新しい備品</h2>
</div>
<div class="l-grid-row clearfix">
  <% @products.each_with_index do |product, i| %>
    <% if i % 2 == 0%>
      <div class="l-grid-row clearfix">
    <% end %>
    <div class="l-grid-6-12 l-align-left">
      <div class="product_small">
	<div class="info l-grid-row">
	  <span class="date">
	    <%= l product.created_at, format: :short %>
	  </span>
	</div>
	<div>
	  <% unless product.lendable? %>
	    <span class="hover_batch">貸出中</span>
	  <% end %>
	  <%= link_to image_tag(product.image.url), product_path(product)%>
	</div>
	<%= link_to truncate(product.name, :length => 30, :separator => "..."), product_path(product)%>
      </div>
    </div>
    <% if i % 2 == 1 %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="l-grid-row see_more">
  <%= link_to "さらにみる",products_path%>

</div>

app/views/home/sp/_side.html.erb
<% if current_user.owner_or_manager? %>
<div class="l-side-row">
    <%= render 'admin/menu_panel' %>
</div>
<% end %>
<div class="l-side-row">
  <%= render 'home/user_lending_status'%>
</div>
<div class="l-side-row">
  <%= render 'home/most_used_tags'%>
</div>