config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => "users/registrations",
    :passwords => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  devise_scope :user do
    delete '/users_icon', to:'users/registrations#delete_icon'
  end
  namespace :admin do
    namespace :member do
      resource :authority, :only => [:show, :update]
      resource :request, :only => [:show, :update]
    end
    namespace :settings do
      resource :slack, :only => [:show, :update]
    end
  end

  resources :products, :only => [:index,:create, :show,:update, :destroy] do
    collection do
      post :import
    end
    resource :tags, :only => [:show,:create, :destroy]
  end
  
  scope :admin do
    resources :products, :only => [:new,:edit] do
      collection do
        get :import_export
      end
    end
    match 'products' => 'products#admin_index', :via => :get, as: 'admin_products'
    match 'lendings' => 'products#admin_lendings', :via => :get, as: 'admin_lendings'
    delete 'products/:id/image', to:'products#delete_image'
  end
  
  resources :lending, :only => [:create, :update]

  namespace :third do
    resource :product_search, :only => [:show]
    match 'image' => 'product_image#show', :via => :get, as: 'load_image'
  end

  resources :lendings
  resources :comments, :only => [:index,:create, :update, :destroy]

end

app/views/admin/_menu_panel.erb
<div class="admin_panel">
  <ul>
    <li class="heading">
      <a href="/">備品</a>
    </li>
    <li>
      <%= link_to "一覧", admin_products_path%>
    </li>
    <li>
      <%= link_to "貸出中の備品一覧", admin_lendings_path %>
    </li>
    <li>
      <%= link_to "追加",new_product_path %>
    </li>
    <li>
      <%= link_to "バックアップ", import_export_products_path%>
    </li>
    <li>
      <%= search_form_for product_query, class: "input_box clearfix" do |f| %>
	<%= f.search_field :name_or_description_cont, class: "l-align-left"%>
	<%= f.submit "検索", class: "l-align-right"%>
      <% end %>
    </li>
  </ul>
  <ul>
    <li class="heading">
      <a href="/">ユーザ</a>
    </li>
    <li>
      <%= link_to "追加と承認", admin_member_request_path %>
    </li>
    <% if current_user.owner? %>
      <li>
	<%= link_to "権限の管理", admin_member_authority_path %>
      </li>
    <% end %>
  </ul>
  <ul>
    <li class="heading">
      <a href="/">設定</a>
    </li>
    <li>
      <%= link_to "Slack通知", admin_settings_slack_path %>
    </li>
  </ul>
</div>

app/views/admin/_side.html.erb
<div class="l-side-row">
  <%= render 'admin/menu_panel' %>
</div>
<div class="l-side-row">
  <%= render 'admin/usage_stats'%>
</div>

app/views/admin/_usage_stats.html.erb
<div class="usage_stats">
  <h1>貸出件数</h1>
  <table>
    <thead>
      <tr>
	<th>累計</th>
	<th>今月</th>
	<th>先月</th>
      </tr>
    </thead>
    <tbody>
      <tr>
	<th><%= Lending.count("all") %></th>
	<th><%= Lending.count("current_month") %></th>
	<th><%= Lending.count("last_month") %></th>
      </tr>
    </tbody>
  </table>
</div>