config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => "users/registrations",
    :passwords => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  devise_scope :user do
    delete '/users_icon', to:'users/registrations#delete_icon'
  end
  namespace :admin do
    namespace :member do
      resource :authority, :only => [:show, :update]
      resource :request, :only => [:show, :update]
    end
    namespace :settings do
      resource :slack, :only => [:show, :update]
    end
  end

  resources :products, :only => [:index,:create, :show,:update, :destroy] do
    collection do
      post :import
    end
    resource :tags, :only => [:show,:create, :destroy]
  end
  
  scope :admin do
    resources :products, :only => [:new,:edit] do
      collection do
        get :import_export
      end
    end
    match 'products' => 'products#admin_index', :via => :get, as: 'admin_products'
    match 'lendings' => 'products#admin_lendings', :via => :get, as: 'admin_lendings'
    delete 'products/:id/image', to:'products#delete_image'
  end
  
  resources :lending, :only => [:create, :update]

  namespace :third do
    resource :product_search, :only => [:show]
    match 'image' => 'product_image#show', :via => :get, as: 'load_image'
  end

  resources :lendings
  resources :comments, :only => [:index,:create, :update, :destroy]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @products = Product.last(6).reverse
    @lendings = Product.unreturned.last(6).reverse
    @tags = ActsAsTaggableOn::Tag.most_used(20)
    @comments = Comment.last(3).reverse
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_most_used_tags.html.erb
<div class="most_used_tags_wrapper">
  <h1>人気のタグ</h1>
  <div class="most_user_tags">
    <div class="tags-wrapper l-grid-row">
      <% @tags.each do |tag|  %>
	<div class="tag">
	  <%= link_to tag, products_path(tag: tag.name)%>
	</div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_pending.html.erb
<h1 class="border_heading">参加の承認待ち</h1>
<p>
  アカウントの登録が完了しました！<br>
  サービスの利用を開始するには、本サービスの管理者よる参加の承認が必要です。<br>
  管理者に参加承認の手続きを行うようにお願いしてください。<br>
</p>

app/views/home/_user_lending_status.html.erb
<div class="user_lending_status">
  <div class="tab-nav clearfix">
    <div class="l-grid-1-2 l-align-left">
      <button class="actived">貸出状況</button>
    </div>
  </div>
  <div class="tab-content">
    <div class="content">
      <ul>
	<% current_user.unreturned_lendings.each do |lending|%>
	<li class="clearfix">
          <div class="l-grid-10-12 l-align-left">
	    <p class="deadline">返却期限：
        <span class="<%= 'overdue' if lending.overdue? %>">
          <%= l lending.deadline, format: :short%></p>
        </span>
	      <%= link_to truncate(lending.product.name, :length => 30, :separator => "..."), product_path(lending.product), class: "title"%>
	  </div>
	  <div class="l-grid-2-12 l-align-right">
	    <%= link_to "返却", lending_path(lending, status: "returned"), method: :patch ,class: "link_btn link_btn_success"%>
	  </div>
	</li>
	<% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div class="l-constrained">
  <% if user_signed_in? %>
    <% if current_user.member? %>
      <%= render "home/pc/home"  %>
    <% else %>
      <%= render "home/pending"%>
    <% end %>
  <% else %>
    <%= render "home/pc/introduction"%>
  <% end %>
</div>

app/views/home/show_smart_phone.html.erb
<div class="l-constrained">
  <% if user_signed_in? %>
    <% if current_user.member? %>
      <%= render "home/sp/home"  %>
    <% else %>
      <%= render "home/pending"%>
    <% end %>
  <% else %>
    <%= render "home/sp/introduction"%>
  <% end %>
</div>