config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => "users/registrations",
    :passwords => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  devise_scope :user do
    delete '/users_icon', to:'users/registrations#delete_icon'
  end
  namespace :admin do
    namespace :member do
      resource :authority, :only => [:show, :update]
      resource :request, :only => [:show, :update]
    end
    namespace :settings do
      resource :slack, :only => [:show, :update]
    end
  end

  resources :products, :only => [:index,:create, :show,:update, :destroy] do
    collection do
      post :import
    end
    resource :tags, :only => [:show,:create, :destroy]
  end
  
  scope :admin do
    resources :products, :only => [:new,:edit] do
      collection do
        get :import_export
      end
    end
    match 'products' => 'products#admin_index', :via => :get, as: 'admin_products'
    match 'lendings' => 'products#admin_lendings', :via => :get, as: 'admin_lendings'
    delete 'products/:id/image', to:'products#delete_image'
  end
  
  resources :lending, :only => [:create, :update]

  namespace :third do
    resource :product_search, :only => [:show]
    match 'image' => 'product_image#show', :via => :get, as: 'load_image'
  end

  resources :lendings
  resources :comments, :only => [:index,:create, :update, :destroy]

end

app/models/product.rb
# -*- coding: utf-8 -*-
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)      default(""), not null
#  description :text
#  image       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#
require 'csv'
class Product < ApplicationRecord
  validates :name, length: {maximum: 96}, presence: true
  validates :description, length: {maximum: 2048}
  has_many :lendings, ->{order ("updated_at DESC")}, dependent: :destroy
  has_many :comments, ->{order ("updated_at ASC")}, dependent: :destroy
  #スコープの追加
  scope :unreturned, -> { joins(:lendings).merge(Lending.unreturned) }
  mount_uploader :image, ImageUploader
  # タグが管理できるようにする
  acts_as_taggable
  after_create :slack_notify_new_product

  def self.ransackable_attributes auth_object = nil
    %w(name description)
  end

  def self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      attrs = row.to_hash.slice("name","description")
      product = Product.new(attrs)
      product.save!
    end
  end
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |model|
        csv << model.attributes.values_at(*column_names)
      end
    end
  end
  # フォームでbase64_imageというフォーム部品を表示させるために必要
  def base64_image
    return @base64_image
  end
  def base64_image=(file)
    @base64_image = file
  end
  
  # 貸出可能 or 貸出中かを返す
  def status
    if self.lendable?
      "returned"
    else
      "unreturned"
    end
  end
  
  # この備品の累計貸出回数
  def count
    self.lendings.length
  end

  # 借りれるかどうか
  def lendable?
    if latest_lending && latest_lending.status == "unreturned"
      # 借りれない
      false
    else
      # 借りれる
      true
    end
  end

  def lending_user
    latest_lending.user
  end

  def overdue?
    latest_lending.overdue?
  end

  def lending_date
    latest_lending.created_at.to_date
  end


  def deadline
    latest_lending.deadline
  end

  def latest_lending
    if self.lendings.first
      self.lendings.first
    else
      nil
    end
  end
  def slack_notify_new_product
    SlackNotificationJob.perform_later("new_product", self.id)
  end
end

app/controllers/products_controller.rb
# -*- coding: utf-8 -*-
class ProductsController < ApplicationController
  include CarrierwaveBase64Uploader
  before_action :authenticate_user!
  before_action :member
  before_action :owner_or_manager, :only => [:admin_index, :new, :create, :edit, :update, :delete_image, :destroy, :import, :admin_lendings]
  def index
    tag = params["tag"]
    query = params["q"]
    if !tag && !query
      @heading = "新しい備品"
      @products = Product.order("created_at DESC").paginate(page: params[:page], :per_page => 10)
    elsif tag
      @heading = "タグ \"#{tag}\" を持つ備品"
      @products = Product.tagged_with(tag).paginate(page: params[:page], :per_page => 10)
    else
      @heading = "\"#{params['q']['name_or_description_cont']}\" の検索結果"
      @q = Product.search(query)
      @products = @q.result(distinct: true).paginate(page: params[:page], :per_page => 10)
    end
    respond_to do |format|
      format.html
      format.csv { send_data Product.to_csv }
    end
  end
  def admin_index
    @products = Product.order("created_at DESC").paginate(page: params[:page], :per_page => 10)
  end

  def admin_lendings
    @products = Product.order("created_at DESC").paginate(page: params[:page], :per_page => 10).unreturned
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    # tag_listにはコンマ区切りでタグを渡す
    # *演算子で配列の値をコンマ区切りにしてる
    if params["tags"]
      @product.tag_list.add(*params["tags"].values)
    end
    if @product.save
      redirect_to new_product_path, notice: "備品を追加しました"
    else
      render 'new'
    end
  end

  def show
    expires_now
    @product = Product.find(params[:id])
    @comments = @product.comments
    gon.jbuilder
    gon.authority = current_user.authority
    gon.user_id = current_user.id
    gon.tags = @product.tag_list
    gon.tags_path = request.path_info + '/tags'
    gon.product_id = @product.id
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end
  def delete_image
    product = Product.find(params[:id])
    product.remove_image!
    if product.save
      render :json => {'status' => 'success'}
    else
      render :json => {'status' => 'faild'}
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to admin_products_path, notice: "備品を削除しました"
  end

  def import
    Product.import(params[:file])
    redirect_to admin_products_path, notice: "備品をインポートしました"
  end
  private
  def product_params
    base64_image = params[:product][:base64_image]
    # base64エンコードの画像が含まれていたら，画像に変換してparamに追加
    unless base64_image.nil? || base64_image.empty?
      params[:product][:image] = base64_conversion(base64_image)
    end
    params.require(:product).permit(:name, :description, :image,:url)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/admin_index.html.erb
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <div class="l-side-col l-grid-3-12 l-align-left">
    <%= render "admin/side" %>
  </div>
  <div class="l-grid-9-12 l-align-left">
    <h2>備品一覧 (全<%= @products.total_entries %>件)</h2>
    <table class="goods_table l-grid-row">
      <thead>
	<tr>
	  <th class="col_goods"">品名</th>
	  <th class="col_date">登録日時</th>
	  <th class="col_times">累計貸出回数</th>
	  <th class="col_status">貸出可否</th>
	  <th ckass="col_edit"></th>
	</tr>
      <tbody>
	<% @products.each do |product|  %>
	  <tr>
	    <td class="col_goods">
	      <%= link_to product.name, product_path(product) %>
	    </td>
	    <td class="col_date"><%= l product.created_at, format: :short%></td>
	    <td class="col_times"><%= product.count %></td>
	    <td class="col_status"><%= product_status(product.status)%></td>
	    <td class="col_edit">
	      <%= link_to "編集", edit_product_path(product), class: "link_btn link_btn_success" %>
	    </td>
	  </tr>
	<% end %>
      </tbody>
    </table>
    <div class="l-constrained pagination">
      <%= will_paginate @products, previous_label: "前", next_label: "次"%>
    </div>
    
  </div>
</div>

app/views/products/admin_index_smart_phone.html.erb
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <%= render "admin/side" %>
  <div class="l-grid-row">
    <h2>備品一覧 (全<%= @products.total_entries %>件)</h2>
    <table class="goods_table l-grid-row">
      <thead>
	<tr>
	  <th class="col_goods"">品名</th>
	  <th class="col_date">登録日時</th>
	  <th class="col_times">累計貸出回数</th>
	  <th class="col_status">貸出可否</th>
	  <th ckass="col_edit"></th>
	</tr>
      <tbody>
	<% @products.each do |product|  %>
	  <tr>
	    <td class="col_goods">
	      <%= link_to product.name, product_path(product) %>
	    </td>
	    <td class="col_date"><%= l product.created_at, format: :short%></td>
	    <td class="col_times"><%= product.count %></td>
	    <td class="col_status"><%= product_status(product.status)%></td>
	    <td class="col_edit">
	      <%= link_to "編集", edit_product_path(product), class: "link_btn link_btn_success" %>
	    </td>
	  </tr>
	<% end %>
      </tbody>
    </table>
    <div class="l-constrained pagination">
      <%= will_paginate @products, previous_label: "前", next_label: "次"%>
    </div>
    
  </div>
</div>

app/views/products/admin_lendings.html.erb
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <div class="l-side-col l-grid-3-12 l-align-left">
    <%= render "admin/side" %>
  </div>
  <div class="l-grid-9-12 l-align-left">
    <h2>貸出中の備品一覧 (全<%= @products.total_entries %>件)</h2>
    <table class="goods_table l-grid-row">
      <thead>
	<tr>
	  <th class="col_goods">品名</th>
	  <th class="col_userid">貸出者ID</th>
	  <th class="col_datesimple">貸出日</th>
	  <th class="col_datesimple">返却期限</th>
	  <th class="col_times">累計貸出回数</th>
	  <th class="col_status">延滞状況</th>
	  <th ckass="col_edit">編集</th>
	</tr>
      </thead>
      <tbody>
	<% @products.each do |product|  %>
	  <tr>
	    <td class="col_goods">
	      <%= link_to product.name, product_path(product) %>
	    </td>
	    <td class="col_userid"><%= product.lending_user.name%></td>
	    <td class="col_datesimple"><%= l product.lending_date, format: :short%></td>
	    <td class="col_datesimple"><%= l product.deadline, format: :short%></td>
	    <td class="col_times"><%= product.count %></td>
	    <td class="col_status"><%= "延滞" if product.overdue?%></td>
	    <td class="col_edit">
	      <%= link_to "編集", edit_product_path(product), class: "link_btn link_btn_success" %>
	    </td>
	  </tr>
	<% end %>
      </tbody>
    </table>
    <div class="l-constrained pagination">
      <%= will_paginate @products, previous_label: "前", next_label: "次"%>
    </div>
    
  </div>
</div>

app/views/products/admin_lendings_smart_phone.html.erb
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <%= render "admin/side" %>
  <div class="l-grid-row">
    <h2>貸出中の備品一覧 (全<%= @products.total_entries %>件)</h2>
    <table class="goods_table l-grid-row">
      <thead>
	<tr>
	  <th class="col_goods">品名</th>
	  <th class="col_userid">貸出者ID</th>
	  <th class="col_datesimple">貸出日</th>
	  <th class="col_datesimple">返却期限</th>
	  <th class="col_times">累計貸出回数</th>
	  <th class="col_status">延滞状況</th>
	  <th ckass="col_edit">編集</th>
	</tr>
      </thead>
      <tbody>
	<% @products.each do |product|  %>
	  <tr>
	    <td class="col_goods">
	      <%= link_to product.name, product_path(product) %>
	    </td>
	    <td class="col_userid"><%= product.lending_user.name%></td>
	    <td class="col_datesimple"><%= l product.lending_date, format: :short%></td>
	    <td class="col_datesimple"><%= l product.deadline, format: :short%></td>
	    <td class="col_times"><%= product.count %></td>
	    <td class="col_status"><%= "延滞" if product.overdue?%></td>
	    <td class="col_edit">
	      <%= link_to "編集", edit_product_path(product), class: "link_btn link_btn_success" %>
	    </td>
	  </tr>
	<% end %>
      </tbody>
    </table>
    <div class="l-constrained pagination">
      <%= will_paginate @products, previous_label: "前", next_label: "次"%>
    </div>
  </div>
</div>
  

app/views/products/edit.html.erb
<%= content_for :javascript do %>
  <%= javascript_include_tag :product_edit_form %>
<% end %>
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <div class="l-grid-3-12 l-align-left l-side-col">
    <%= render "admin/side" %>
  </div>
  <div class="l-grid-9-12 l-align-left">
    <h2>備品の編集</h2>
    <%= form_for @product , :html => {:multipart => true, :class => "goods_form"} do |f| %>
      <% if @product.errors.any? %>
	<div class="l-grid-row">
	  <ul>
	    <% @product.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
      <% end %>
      <div class="l-grid-row clearfix">
	<div class="l-grid-2-12 l-align-left">
	  <%= f.label :name, "品名(必須)" %>
	  <div class="annotation">※96文字以内</div>
	</div>
	<div class="l-grid-10-12 l-align-left">
	  <%= f.text_field :name, :class => "input"%>
	</div>
      </div>
      <div class="l-grid-row clearfix">
	<div class="l-grid-2-12 l-align-left">
	  <%= f.label :description, "説明(必須)"%>
	  <div class="annotation">
	    ※2048文字以内</div>
	</div>
	<div class="l-grid-10-12 l-align-left">
	  <%= f.text_area :description, :class => "textarea"%>
	</div>
      </div>
      <div class="l-grid-row clearfix">
	<div class="l-grid-2-12 l-align-left">
	  <label>画像</label>
	</div>
	<div class="l-grid-10-12 l-align-left">
	  <% if @product.image? %>
	    <div class="thumbnail" data-bind="if: product_edit_form_vm.image_exist">
	      <%= image_tag @product.image.url%><br>
	      <button id="delete_image", type="button" data-bind="click: product_edit_form_vm.delete_image " class="button button-warning">画像を削除</button>
	    </div>
	    <script>
	     //もし画像が存在すれば，画像を表示させる
	     root_vm["product_edit_form_vm"].image_exist(true);
	    </script>
	  <% end %>
	  <%= f.hidden_field :base64_image, :data => {:bind => "ifnot : product_edit_form_vm.image_exist"} %>
	  <div data-bind="visible : !product_edit_form_vm.image_exist()">
	    <div class="crop-container"><!-- - ここに編集画面が追加されます -->
	    </div>
	    <div class="l-grid-row clearfix">
	      <div class="l-grid-3-8 l-align-left">
		<button id="rotateLeft" type="button">左回転</button>
		<button id="rotateRight" type="button">右回転</button>
	      </div>
	      <div class="l-grid-5-8 l-align-left">
		<!-- ・ファイルの選択 -->
		<input type="file" id="loadFile">
	      </div>
	    </div>
	    <div class="l-grid-row clearfix loadFileWapper">
	      <div class="l-grid-1-2">
		<!-- ・拡大縮小 -->
		縮小
	      <input type="range" max="100" min="0" id="zoom">
	      拡大
	      </div>
	    </div>
	  </div>
	</div>
      </div>
      <div class="l-grid-row clearfix">
	
	<%= f.submit "更新", class: "button button-success l-align-right" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/edit_smart_phone.html.erb
<%= content_for :javascript do %>
  <%= javascript_include_tag :product_edit_form %>
<% end %>
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <%= render "admin/side" %>
  <div class="l-grid-row">
    <h2>備品の編集</h2>
    <%= form_for @product , :html => {:multipart => true, :class => "goods_form"} do |f| %>
      <% if @product.errors.any? %>
	<div class="l-grid-row">
	  <ul>
	    <% @product.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
      <% end %>
      <div class="l-grid-row clearfix">
	  <%= f.label :name, "品名(必須)" %>
	  <div class="annotation">※96文字以内</div>
	  <%= f.text_field :name, :class => "input"%>
      </div>
      <div class="l-grid-row clearfix">
	  <%= f.label :description, "説明(必須)"%>
	  <div class="annotation">
	    ※2048文字以内</div>
	  <%= f.text_area :description, :class => "textarea"%>
      </div>
      <div class="l-grid-row clearfix">
	<div class="l-grid-row l-align-left">
	  <label>画像</label><br>
	  <span>スマートフォン版からは画像を変更できません。</span>
	</div>
      </div>
      <div class="l-grid-row clearfix">
	
	<%= f.submit "更新", class: "button button-success l-align-right" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/import_export.html.erb
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <div class="l-side-col l-grid-3-12 l-align-left">
    <%= render "admin/side"%>
  </div>
  <div class="l-grid-9-12 l-align-left">
    <h2>備品データのインポート/エクスポート</h2>
    <p>CSV形式で備品データのインポート/エクスポートができます。<br>※画像のデータは含みません。</p>
    <h3>インポート</h3>
    <%= form_tag import_products_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "インポート" %>
    <% end %>
    <h3>エクスポート</h3>
    <%= link_to 'ダウンロード', products_path(format: 'csv')%>
  </div>
</div>

app/views/products/import_export_smart_phone.html.erb
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <%= render "admin/side"%>
  <div class="l-grid-row l-align-left">
    <h2>備品データのインポート/エクスポート</h2>
    <p>CSV形式で備品データのインポート/エクスポートができます。<br>※画像のデータは含みません。</p>
    <h3>インポート</h3>
    <%= form_tag import_products_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "インポート" %>
    <% end %>
    <h3>エクスポート</h3>
    <%= link_to 'ダウンロード', products_path(format: 'csv')%>
  </div>
</div>

app/views/products/new_smart_phone.html.erb
<div class="l-constrained clearfix">
  <h1>管理画面</h1>
  <%= render "admin/side" %>
  <div class="l-grid-row">
    <h2>備品の追加</h2>
    <span>スマートフォン版では対応していません。</span>
  </div>
</div>

app/views/products/show.html.erb
<%= content_for :javascript do %>
  <%= javascript_include_tag :product_tags %>
  <%= javascript_include_tag :product_comments %>
<% end %>
<div class="l-constrained">
  <div class="l-grid-row clearfix">
    <div class="l-grid-6-12 l-align-left">
      <h1>備品詳細</h1>
    </div>
    <div class="l-grid-6-12 l-align-right">
      <% if current_user.owner_or_manager? %>
	<div class="product_toolbox">
	  <%= link_to "削除",product_path(@product), class: "link_btn link_btn_warning", :method => :delete, data:{:confirm => "本当に削除しますか？"}%>
	  <%= link_to "編集", edit_product_path(@product), class: "link_btn link_btn_info"%>
	</div>
      <% end %>
    </div>
  </div>
  <div class="block_content product_small clearfix">
    <div class="l-grid-row clearfix">
      <div class="l-grid-2-12 l-align-left">
	<div class="inner_offset">
	  <%= image_tag @product.image.url %>
	  <%= render "home/pc/lending_data", product: @product%>
	</div>
      </div>
      <div class="l-grid-8-12 l-align-left">
	<div class="inner_offset">
	  <h1><%= @product.name %></h1>

	  <p><%= @product.description %></p>
	  <% if @product.url != "" %>
	    <%= link_to "商品リンク", @product.url%>
	  <% end %>
	</div>
      </div>
      <div class="l-grid-2-12 l-align-left">
	<div class="vertical_btns">
	  <% if @product.lendable? %>
	    <%= link_to "借りる",lending_index_path(product_id: @product.id),method: :post,class: "link_btn link_btn_success" %>
	  <% elsif @product.latest_lending.user == current_user %>
	    <%= link_to "返却する", lending_path(@product.latest_lending, status: "returned"), method: :patch ,class: "link_btn link_btn_success"%>
	  <% else %>
	    <span class="link_btn link_btn_default">貸出中です</span>
	  <% end %>
	
	</div>
      </div>
    </div>
    <div class="l-grid-row tags-wrapper" data-bind="with: root_vm.product_tags_vm">
      <button class="edit_button" data-bind="click:toggle, text:btn_text"></button>
      <div class="add_box" data-bind="visible: editing" style="display:none;">
	<input type="text" data-bind="value: input, click: reset_message">
	<button data-bind="click: addTag">追加</button>
	<span class="error" data-bind="text:error_message"></span>
	
      </div>
      <!-- ko foreach: tags -->
      <div class="tag">
	<a href="" data-bind="text: $data, attr: {href: '/products?tag='+encodeURIComponent($data)}"></a>
	<button data-bind="visible: $parent.editing, click: $parent.remove">x</button>
      </div>
      <!-- /ko -->
    </div>
  </div>
  
  <h2>コメント</h2>
  <div class="product_comments block_content" data-bind="with: root_vm.product_comments_vm">
    <div data-bind="foreach: {data: comments, afterAdd: showEffect, beforeRemove: hideEffect}">
    <div class="product_comment l-grid-12-12 clearfix l-align-center">
      <div class="l-grid-1-12 l-align-left">
        <div class="inner_offset">
	  <img data-bind="attr:{src: $parent.url(user.image)}">
	</div>
      </div>
      <div class="l-grid-11-12 l-align-left">
	<div class="info l-grid-row clearfix">
	  <div class="l-grid-10-12 l-align-left">
	    <span data-bind="text:user.name"></span> - <span data-bind="text: created_at">2014/10/10</span>
	  </div>
	</div>
	<div class="fbox font-large" data-bind="text: content"></div>
	<div class="l-grid-1-12 l-align-right">
	  <button class="button button-warning" data-bind="visible: user.id == $parent.user_id || $parent.authority == 'owner' || $parent.authority == 'manager', click: $parent.remove">削除</button>
	</div>
      </div>
    </div>
    </div>
    <h3 class="border_heading">コメントする</h3>
    <div class="product_comment clearfix">
      <form class="product_comment_form">
	<div class="l-grid-1-12 l-align-left">
          <div class="inner_offset">
	    <%= image_tag current_user.image.url %>
	  </div>
	</div>
	<div class="l-grid-11-12 l-align-left">
	  <div class="info"><span>@<%= current_user.name%></span></div>
	  <div class="fbox">
	    <textarea data-bind="value: textarea, click: reset_message"></textarea>
	  </div>
	  <button class="button button-success l-align-right" data-bind="click: create">送信</button>
	  <div class="error l-align-right" data-bind="text: error_message"></div>
	    <div class="success l-align-right" data-bind="text: success_message"></div>
	</div>
      </form>
    </div>
  </div>
</div>

app/views/products/show_smart_phone.html.erb
<%= content_for :javascript do %>
  <%= javascript_include_tag :product_tags %>
  <%= javascript_include_tag :product_comments %>
<% end %>
<div class="l-constrained">
  <div class="l-grid-row clearfix">
    <div class="l-grid-6-12 l-align-left">
      <h1>備品詳細</h1>
    </div>
    <div class="l-grid-6-12 l-align-right">
      <% if current_user.owner_or_manager? %>
	<div class="product_toolbox">
	  <%= link_to "削除",product_path(@product), class: "link_btn link_btn_warning", :method => :delete, data:{:confirm => "本当に削除しますか？"}%>
	  <%= link_to "編集", edit_product_path(@product), class: "link_btn link_btn_info"%>
	</div>
      <% end %>
    </div>
  </div>
  <div class="block_content product_small clearfix">
    <div class="l-grid-row clearfix">
	<div class="vertical_btns">
	  <% if @product.lendable? %>
	    <%= link_to "借りる",lending_index_path(product_id: @product.id),method: :post,class: "link_btn link_btn_success" %>
	  <% elsif @product.latest_lending.user == current_user %>
	    <%= link_to "返却する", lending_path(@product.latest_lending, status: "returned"), method: :patch ,class: "link_btn link_btn_success"%>
	  <% else %>
	    <span class="link_btn link_btn_default">貸出中です</span>
	  <% end %>
	
	</div>
    </div>
    <div class="l-grid-row clearfix">
      <div class="l-grid-4-12 l-align-left">
	<div class="inner_offset">
	  <%= image_tag @product.image.url %>
	</div>
      </div>
      <div class="l-grid-8-12 l-align-left">
	<div class="inner_offset">
	  <h1><%= @product.name %></h1>
	  <p><%= @product.description %></p>
	  <% if @product.url != "" %>
	    <%= link_to "商品リンク", @product.url%>
	  <% end %>
	</div>
      </div>
    </div>
    
    <div class="l-grid-row tags-wrapper" data-bind="with: root_vm.product_tags_vm">
      <button class="edit_button" data-bind="click:toggle, text:btn_text"></button>
      <div class="add_box" data-bind="visible: editing" style="display:none;">
	<input type="text" data-bind="value: input, click: reset_message">
	<button data-bind="click: addTag">追加</button>
	<span class="error" data-bind="text:error_message"></span>
	
      </div>
      <!-- ko foreach: tags -->
      <div class="tag">
	<a href="" data-bind="text: $data, attr: {href: '/products?tag='+encodeURIComponent($data)}"></a>
	<button data-bind="visible: $parent.editing, click: $parent.remove">x</button>
      </div>
      <!-- /ko -->
    </div>
  </div>
  
  <h2>コメント</h2>
  <div class="product_comments block_content" data-bind="with: root_vm.product_comments_vm">
    <div data-bind="foreach: {data: comments, afterAdd: showEffect, beforeRemove: hideEffect}">
    <div class="product_comment l-grid-12-12 clearfix l-align-center">
      <div class="l-grid-3-12 l-align-left">
        <div class="inner_offset">
	  <img data-bind="attr:{src: $parent.url(user.image.image.url)}">
	</div>
      </div>
      <div class="l-grid-9-12 l-align-left">
	<div class="info l-grid-row clearfix">
	  <span data-bind="text:user.name"></span> - <span data-bind="text: created_at">2014/10/10</span>
	</div>
	<div class="fbox font-large">
	  <span data-bind="text: content"></span>
	</div>
	<div class="l-grid-5-12 l-align-right">
	  <button class="button button-warning" data-bind="visible: user.id == $parent.user_id || $parent.authority == 'owner' || $parent.authority == 'manager', click: $parent.remove">削除</button>
	</div>
      </div>
    </div>
    <h3 class="border_heading">コメントする</h3>
    <div class="product_comment clearfix">
      <form class="product_comment_form">
	<div class="l-grid-3-12 l-align-left">
          <div class="inner_offset">
	    <%= image_tag current_user.image.url %>
	  </div>
	</div>
	<div class="l-grid-9-12 l-align-left">
	  <div class="info"><span>@<%= current_user.name%></span></div>
	  <div class="fbox">
	    <textarea data-bind="value: textarea, click: reset_message"></textarea>
	  </div>
	  <button class="button button-success l-align-right" data-bind="click: create">送信</button>
	  <div class="error l-align-right" data-bind="text: error_message"></div>
	    <div class="success l-align-right" data-bind="text: success_message"></div>
	</div>
      </form>
    </div>
  </div>
</div>